#!/bin/bash

# List of layouts to cycle through (e.g., you can list other layouts if desired)
LAYOUTS=("us" "br" "fr" "de" "es")
CURRENT_LAYOUT=$(setxkbmap -query | grep layout | awk '{print $2}')

# Display current layout for i3blocks
echo "Layout: $CURRENT_LAYOUT"

# On left-click, cycle to the next layout
if [ "$BLOCK_BUTTON" == "3" ]; then
    # Find the index of the current layout
    for i in "${!LAYOUTS[@]}"; do
        if [[ "${LAYOUTS[$i]}" == "$CURRENT_LAYOUT" ]]; then
            # Set the next layout in the list, or wrap to the beginning
            NEXT_LAYOUT="${LAYOUTS[$(( (i + 1) % ${#LAYOUTS[@]} ))]}"
            setxkbmap "$NEXT_LAYOUT"
            echo "Switched to $NEXT_LAYOUT"
            break
        fi
    done
fi

# On right-click, display a menu of layouts to choose from (using rofi or dmenu)
if [ "$BLOCK_BUTTON" == "1" ]; then
    CHOSEN_LAYOUT=$(printf "%s\n" "${LAYOUTS[@]}" | rofi -dmenu -p "Select Layout")
    if [[ " ${LAYOUTS[*]} " == *" $CHOSEN_LAYOUT "* ]]; then
        setxkbmap "$CHOSEN_LAYOUT"
        echo "Switched to $CHOSEN_LAYOUT"
    fi
fi

