#!/usr/bin/env bash


# wshowkeys [-b|-f|-s #RRGGBB[AA]] [-F font] [-t timeout]
#     [-a top|left|right|bottom] [-m margin] [-o output]
#
wshowkeys -a right -a bottom -m 150 -F 'jetbrains mono 24' -t 1.5
