#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Documents ~/Documents/school ~/Documents/work ~/Documents/work/domatica ~/Documents/work/personal ~/Documents/projects ~/ ~/Documents/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

zellij attach "$selected_name" -c options --default-cwd "$selected"
